### ISSUE TITLE
Definir un nombre para la web

### ISSUE THREAD

**Issue by facuezeperalta** [grupoA7ISPC/ProyectoISPCGrupo55#11]

**Comment by facuezeperalta** [comment]
- FitUp
- Salud+
-

**Comment by andresito-luna** [comment]
Ya deje aporte en la rama y doc destinado a tal fin.

**Comment by Silvina-Dew** [comment]
- Marca-Paso
- Depor-Ty
- FitKing

**Comment by HoracieQuiroga** [comment]
•	Rings
•	Movin
•	The Movings

**Comment by estebanmartins** [comment]
• MyProgressFit
• Agenda Fitness
• RuFitness
Dejo asentado esto tambien en la branch decisiones y votaciones.

**Comment by PaylemanC** [comment]
Me gustan más las ideas ya propuestas, así que sin ánimos de alargar la lista, yo solo dejo una opción: 
• IdealFit.

**Comment by Silvina-Dew** [comment]
Dejo asentado los nombres propuestos en la seccion correspondiente.

**Comment by FlorenciaRoux** [comment]
Dejo asentados los nombres propuestos

**Comment by verofx** [comment]
- RoutineFit
- FitHealth o FHealth
- TrainingFit o FitTraining

**Comment by misterio07** [comment]
dejo mi propuesta de nombre: 
MisRutinas.fit
y además lo dejo en  en el archivo correspondiente
