### ISSUE TITLE
Realizar el mapa de sitio

### ISSUE THREAD

**Issue by facuezeperalta** [grupoA7ISPC/ProyectoISPCGrupo55#12]

**Comment by facuezeperalta** [comment]
Herramienta sugerida para armarlo: 
https://app.diagrams.net/

**Comment by andresito-luna** [comment]
Copio lo que Silvina puso en el chat:
https://www.lucidchart.com/pages/es/ejemplos/mapa-de-sitio-online

https://images.app.goo.gl/JhwoPFxhFJKzLDP58.

**Comment by andresito-luna** [comment]
Considero que tendriamos que estar todos asignados a esta tarea.

**Comment by verofx** [comment]
![image](https://user-images.githubusercontent.com/106456645/193488901-1f860e46-96d1-4585-8730-62bed46b4382.png)
