### ISSUE TITLE
Documento IEEE830 - 1.3 Personal involucrado

### ISSUE THREAD

**Issue by PaylemanC** [grupoA7ISPC/ProyectoISPCGrupo55#3]
Adición de tablas del **personal involucrado** del documento de requerimientos de software, entendiéndose como "_nombre, rol, categoría profesional, responsabilidad e información de contacto de los involucrados en el desarrollo de la aplicación web_".

**Comment by andresito-luna** [comment]
Agregué mis datos a la sección.

**Comment by fede9087** [comment]
Datos agregados a la sección.

**Comment by Silvina-Dew** [comment]
Agregue mis datos al documento asignado.
