### ISSUE TITLE
Gestion del Hosting

### ISSUE THREAD

**Issue by facuezeperalta** [grupoA7ISPC/ProyectoISPCGrupo55#44]
Búsqueda y gestión de un Hosting para alojar la página institucional .

**Comment by andresito-luna** [comment]
Perfecto facu, me pongo con esto ya mismo.
Mi propuestaes  tambien de avanzar con el nombre de dominio en Nic.ar. Si te parece asigname la issue correspondiente.

**Comment by andresito-luna** [comment]
## Como Crear Cuenta En Oracle Cloud y servidores VPS gratis.
Me basé en articulos y videos del sitio `APUNTES IT`. <br> Los dos primeros corresponden a los creados originalmente: <br>
[Articulo: ¿Cómo obtener 2 VPS GRATIS para SIEMPRE?](https://apuntesit.tk/tutoriales/como-obtener-2-vps-gratis-para-siempre/). `*links no se abren en nueva pestaña automaticamente*`<br>
[Video: ¿Cómo obtener 2 VPS GRATIS para SIEMPRE?](https://youtu.be/uBvZq-MhAB4). <br>

Los que sigue son actualizaciones: <br>
[Articulo: Obtén 3 VPS GRATIS](https://apuntesit.tk/tutoriales/3-vps-gratis/).<br>
[Video: Obtén 3 VPS GRATIS](https://youtu.be/ypUFAa6ee7g).

Recomiendo leer y ver en el orden sugerido.
### ***Saludos!***

**Comment by andresito-luna** [comment]
Tarea completada.
